### ISSUE TITLE
Keyword Documentation links point to old imap library

### ISSUE THREAD

**Issue by sparkymartin** [lasselindqvist/robotframework-imaplibrary#12]
The Keyword Documentation links all point to the old imap library. I get that the keywords may be the same, but the version information is different.

**Comment by lasselindqvist** [comment]
Readme has link to https://lasselindqvist.github.io/robotframework-imaplibrary2/doc/ImapLibrary.html but I might have missed other links. Any PRs are welcome.

Edit: the first link has been changed, the others not in readme.

**Comment by lasselindqvist** [comment]
Those that I found have been fixed.
