### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by navrkald** [lasselindqvist/robotframework-imaplibrary#16]
In many companies the IMAP ports 143 and 993 are blocked by firewall and to access internet it is needed to use proxy so current version of this library can not be used there. The IMAP4 and IMAP4_SSL classes does not support directly passing the proxy setting however it is possible to inherit from these classes and program proxy support e.g. like shown on example: https://gist.github.com/sstevan/efccf3d5d3e73039c21aa848353ff52f

**Comment by navrkald** [comment]
Let me try to implement it.

**Comment by navrkald** [comment]
Hello @lasselindqvist , the proxy support is done. Could you pls check my PR? I have tested the code using our internal proxy and it was working well.

Thx David.

**Comment by lasselindqvist** [comment]
Thanks. I will try to release this within a week to PyPi.
