### ISSUE TITLE
Update proxy documentation

### ISSUE THREAD

**Issue by navrkald** [lasselindqvist/robotframework-imaplibrary#19]
Hello @lasselindqvist, thx for merging and release new version containing proxy implementation from #16, but could you pls update as well [Documentation](https://lasselindqvist.github.io/robotframework-imaplibrary2/doc/ImapLibrary.html#Open%20Mailbox) to contain new parameters in [open_mailbox](https://github.com/lasselindqvist/robotframework-imaplibrary2/blob/master/src/ImapLibrary2/__init__.py#L271) method:
```python
        - ``proxy_host``: Proxy host to connect via. (Default None)
        - ``proxy_port``: Proxy port to connect via. (Default None)
        - ``proxy_user``: Proxy username to connect via. (Default None)
        - ``proxy_password``: Proxy password to connect via. (Default None)
        - ``proxy_type``: Proxy type to connect via. Available values are: http, socks4, socks5 (Default http)
```

**Comment by lasselindqvist** [comment]
Thanks for the reminder. It should be now available at https://lasselindqvist.github.io/robotframework-imaplibrary2/doc/ImapLibrary2.html#Open%20Mailbox
Note the update in the link from ImapLibrary to ImapLibrary2.
