### ISSUE TITLE
Wait For Email: UID SEARCH Failure due to backend error

### ISSUE THREAD

**Issue by bobmeliev** [lasselindqvist/robotframework-imaplibrary#2]
Wait For Email is failing if specify sender argument.

`${latest}=    Wait For Email    subject=Welcome!    timeout=30
`

Works fine but if you specify sender then it starts failing.

`${latest}=    Wait For Email    sender=noreply@example.com    subject=Welcome!    timeout=30`

Fails with error:

> FAIL : imap.search error: NO, [b'[UNAVAILABLE] UID SEARCH Failure due to backend error.

**Comment by lasselindqvist** [comment]
The error message suggests that the problem might lie in the email server failing to handle the request.
Which email provider is this?

**Comment by bobmeliev** [comment]
I'm using https://mail.yandex.com/

**Comment by bobmeliev** [comment]
Cannot reproduce the issue with Gmail account. Closing the ticket.
