### ISSUE TITLE
non-ascii characters in email subject cannot be encoded

### ISSUE THREAD

**Issue by hiob95** [lasselindqvist/robotframework-imaplibrary#24]
When I call the function "Wait For Email" with the parameter "subject" containing special characters (umlaute), I receive the following error: "UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 5: ordinal not in range(128)" This is caused by the following line in _check_emails: typ, msgnums = self._imap.uid('search', None, *criteria), which assumes ascii characters. Is there a way to account for utf-8 characters?
I have tried this solution: https://stackoverflow.com/questions/63685324/searching-for-utf-8-encoded-subjects-with-imaplib
It worked, but then I run into a follow-up issue with the function "Get Links From Email", receiving the error: " get_email_body called on multipart email 'Bestätigen'. Please first use method walk_multipart_email"

**Comment by lasselindqvist** [comment]
https://github.com/lasselindqvist/robotframework-imaplibrary2/issues/22 should have handled these. Are you using the latest version?

**Comment by hiob95** [comment]
Yes I am using version 0.4.2. So I realized, there are two issues here.  #22 addresses decoding problems of the email body for a given email index. I am getting the "UnicodeEncodeError" when searching for an email index that has a subject with special characters, which is not part of this fix, since the function get_email_body() is not called in Wait For Email. 

Secondly, regardless of that problem, I am not able to decode multipart emails, since the relevant function walk_multipart_email() is never called in the source code. #21 might be related to this.

**Comment by BratishkaAlex** [comment]
I have experienced the same issue, email's title contains word 'contraseña' itself and I am facing this issue 'UnicodeEncodeError: 'ascii' codec can't encode character '\xf1' in position 24: ordinal not in range(128)', library version is 0.4.2

**Comment by shisrafilov** [comment]
The same for me, but I use Cyrillic symbols: "Підтвердження".

**Comment by lasselindqvist** [comment]
I will happily merge any fix to this if someone can provide such a thing.

**Comment by shisrafilov** [comment]
I created a new pull request for this issue https://github.com/lasselindqvist/robotframework-imaplibrary2/pull/25

**Comment by lasselindqvist** [comment]
Released in 0.4.3: https://pypi.org/project/robotframework-imaplibrary2/0.4.3/

**Comment by shisrafilov** [comment]
> Released in 0.4.3: https://pypi.org/project/robotframework-imaplibrary2/0.4.3/

Alarm! Looks like I did something wrong while merging and squashing and code isn't working even with ascii symbols.

**Comment by lasselindqvist** [comment]
> > Released in 0.4.3: https://pypi.org/project/robotframework-imaplibrary2/0.4.3/
> 
> Alarm! Looks like I did something wrong while merging and squashing and code isn't working even with ascii symbols.

https://github.com/lasselindqvist/robotframework-imaplibrary2/pull/25/files this is the full change.

**Comment by shisrafilov** [comment]
@lasselindqvist the problem was in _check_emails method. I've just fixed it.

**Comment by lasselindqvist** [comment]
I don't currently have a setup for testing with actual live servers and messages, so I will just merge the fix-up.

**Comment by shisrafilov** [comment]
Will you make a new release for the last merge?

**Comment by lasselindqvist** [comment]
Released as https://pypi.org/project/robotframework-imaplibrary2/0.4.4/

**Comment by shisrafilov** [comment]
Thank you so much!

**Comment by codci** [comment]
hello @lasselindqvist 
I made a small update to handle this issue, could you please take a look to https://github.com/lasselindqvist/robotframework-imaplibrary2/pull/32 
Thanks in advance!

**Comment by codci** [comment]
Hi @lasselindqvist 
could you please release new version after fix ☝️

**Comment by lasselindqvist** [comment]
I will release it this week.

**Comment by lasselindqvist** [comment]
Released in robotframework-imaplibrary2 0.4.7
