### ISSUE TITLE
Latest version (0.4.7) doesn't work with Office365 & Exchange. 

### ISSUE THREAD

**Issue by falcon030** [lasselindqvist/robotframework-imaplibrary#34]
I just tested my pull request (Added IMAP since and before search parameters) and noticed that it doesn't work with Office365 & Exchange!
I made my pull request based on version 0.4.6 (Yeah stupid, me you should check if there is a new version), but version 0.4.7 breaks support for Office365 & Exchange because they only support US-ASCII as a charset for search.
Commenting the following line fixes it for me but also undoes the change of version 0.4.7.

`search_cmd = search_cmd[:1] + ['CHARSET', 'UTF-8'] + search_cmd[2:]`

Also the is an error in the following line:

`raise Exception('imap.search error: %s, %s, criteria=%s' % (typ, msgnums, criteria))`

The variable `criteria `doesn't exists, this should be `search_cmd`

**Comment by lasselindqvist** [comment]
Would your testing mean that 0.4.7 is anyway broken for Office365 & Exchange?

(I have not tested it myself at all, I trusted the comment in https://github.com/lasselindqvist/robotframework-imaplibrary2/pull/32

If 0.4.7 is anyway broken due to the fix attempt, one solution of course is to just simply revert it.

**Comment by falcon030** [comment]
I submitted a pull request to fix this. I made the UTF-8 encoding for the search criteria optional.

**Comment by falcon030** [comment]
@lasselindqvist Any plans to make version 0.4.8 available as a new release?

**Comment by lasselindqvist** [comment]
https://pypi.org/project/robotframework-imaplibrary2/0.4.8/

This has now been released.
