### ISSUE TITLE
Problem with downloading attachments of which the filename is encoded.

### ISSUE THREAD

**Issue by falcon030** [lasselindqvist/robotframework-imaplibrary#39]
@lasselindqvist I had a problem with downloading PDF attachments that where send with outlook365, so I submitted a [pull request](https://github.com/lasselindqvist/robotframework-imaplibrary2/pull/38) to fix this.

**Comment by lasselindqvist** [comment]
https://github.com/lasselindqvist/robotframework-imaplibrary2/pull/38 merged.
