### ISSUE TITLE
Delete All Emails keyword is not deleting all emails

### ISSUE THREAD

**Issue by bobmeliev** [lasselindqvist/robotframework-imaplibrary#6]
For some reason keyword is deleting only one email but not all emails in inbox folder. No any errors or exceptions.

**Comment by lasselindqvist** [comment]
Which email server did you use to reproduce this? How many emails in total exists when running this?
Relevant code is here: https://github.com/lasselindqvist/robotframework-imaplibrary2/blob/master/src/ImapLibrary2/__init__.py#L108

**Comment by bobmeliev** [comment]
Lemme check with Gmail server, seems these issues are related to email server.

**Comment by bobmeliev** [comment]
Tested with Gmail account and keyword works properly. Seems there is nothing can be done. Closing the issue.
