### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by lasselindqvist** [lasselindqvist/robotframework-imaplibrary#8]
Release new version. 
Currently https://github.com/lasselindqvist/robotframework-imaplibrary2/pull/7 is unreleased.

**Comment by macejiko** [comment]
@lasselindqvist any news on that? :(

**Comment by lasselindqvist** [comment]
Got busy and forgot, I will do it today. :)

**Comment by lasselindqvist** [comment]
The twine syntax check on the README has problems again, so it might take some time to get it released.

**Comment by lasselindqvist** [comment]
0.3.6 is available (0.3.5 is the same, but new deploy fixed issues with showing the readme)
